apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  labels:
    name: myapp-pod
spec:
# add the nodeSelector label here
  containers:
  - name: myapp
    image: registry.lab.example.com:5000/openshift/hello-openshift
    ports:
      - name: myapp
        containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: myapp-service
spec:
  ports:
  - name: 8080-tcp
    port: 8080
    protocol: TCP
    targetPort: 8080
    nodePort: 30080
    name: myapp
  selector:
    name: myapp-pod
  type: NodePort
---
apiVersion: v1
kind: Route
metadata:
  name: myapp-route
  labels: 
    name: myapp-pod
spec:
  host: cluster.apps.lab.example.com
  to:
    kind: Service
    name: myapp
