kind: LDAPSyncConfig
apiVersion: v1
url: "ldap://services.lab.example.com:389"
insecure: true
rfc2307:
    groupsQuery:
        baseDN: "cn=customer,ou=Roles,dc=redhat,dc=com"
        scope: sub
        derefAliases: never
        filter: (objectClass=groupOfNames)
    groupUIDAttribute: dn
    groupNameAttributes: [ cn ]
    groupMembershipAttributes: [ member ]
    usersQuery:
        baseDN: "ou=people,dc=redhat,dc=com"
        scope: sub
        derefAliases: never
    userUIDAttribute: dn
    userNameAttributes: [ uid ]
    tolerateMemberNotFoundErrors: false
    tolerateMemberOutOfScopeErrors: false