apiVersion: v1
kind: DeploymentConfig
metadata:
  creationTimestamp: null
  generation: 1
  labels:
    component: kibana
    logging-infra: kibana
    provider: openshift
  name: logging-kibana
spec:
  replicas: 1
  selector:
    component: kibana
    logging-infra: kibana
    provider: openshift
  strategy:
    activeDeadlineSeconds: 21600
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      creationTimestamp: null
      labels:
        component: kibana
        logging-infra: kibana
        provider: openshift
      name: logging-kibana
    spec:
      containers:
      - env:
        - name: ES_HOST
          value: logging-es
        - name: ES_PORT
          value: "9200"
        - name: KIBANA_MEMORY_LIMIT
          valueFrom:
            resourceFieldRef:
              containerName: kibana
              divisor: "0"
              resource: limits.memory
        image: registry.lab.example.com:5000/openshift3/logging-kibana:latest
        imagePullPolicy: Always
        name: kibana
        resources:
          limits:
            memory: 736Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/kibana/keys
          name: kibana
          readOnly: true
      - env:
        - name: OAP_BACKEND_URL
          value: http://localhost:5601
        - name: OAP_AUTH_MODE
          value: oauth2
        - name: OAP_TRANSFORM
          value: user_header,token_header
        - name: OAP_OAUTH_ID
          value: kibana-proxy
        - name: OAP_MASTER_URL
          value: https://kubernetes.default.svc.cluster.local
        - name: OAP_PUBLIC_MASTER_URL
          value: https://master1.lab.example.com:443
        - name: OAP_LOGOUT_REDIRECT
          value: https://master1.lab.example.com:443/console/logout
        - name: OAP_MASTER_CA_FILE
          value: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        - name: OAP_DEBUG
          value: "False"
        - name: OAP_OAUTH_SECRET_FILE
          value: /secret/oauth-secret
        - name: OAP_SERVER_CERT_FILE
          value: /secret/server-cert
        - name: OAP_SERVER_KEY_FILE
          value: /secret/server-key
        - name: OAP_SERVER_TLS_FILE
          value: /secret/server-tls.json
        - name: OAP_SESSION_SECRET_FILE
          value: /secret/session-secret
        - name: OCP_AUTH_PROXY_MEMORY_LIMIT
          valueFrom:
            resourceFieldRef:
              containerName: kibana-proxy
              divisor: "0"
              resource: limits.memory
        image: registry.lab.example.com:5000/openshift3/logging-auth-proxy:latest
        imagePullPolicy: Always
        name: kibana-proxy
        ports:
        - containerPort: 3000
          name: oaproxy
          protocol: TCP
        resources:
          limits:
            memory: 96Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /secret
          name: kibana-proxy
          readOnly: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: aggregated-logging-kibana
      serviceAccountName: aggregated-logging-kibana
      terminationGracePeriodSeconds: 30
      volumes:
      - name: kibana
        secret:
          defaultMode: 420
          secretName: logging-kibana
      - name: kibana-proxy
        secret:
          defaultMode: 420
          secretName: logging-kibana-proxy
  test: false
  triggers:
  - type: ConfigChange
status:
  availableReplicas: 0
  latestVersion: 0
  observedGeneration: 0
  replicas: 0
  unavailableReplicas: 0
  updatedReplicas: 0